In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv(r'Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
x = dataset[['CreditScore', 'Geography','Gender','Age','Tenure',
             'Balance','NumOfProducts','HasCrCard','IsActiveMember']]
y = dataset['Exited']
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  
0             1               1  
1             0               1  
2             1               0  
3             0               0  
4             1               1  
...         ...             ...  
9995          1               0  
9996          1               1  
9997          0               1  
9998          1               0  
9999          1               0  

[10000 rows x 9 columns]

In [4]:
x['Gender'] = dataset['Gender'].map({'Female':0, 'Male': 1})
x['Geography'] = dataset['Geography'].map({'France':0, 'Spain': 1, 'Germany': 2})

<ipython-input-4-a5ff8b17c4c4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Gender'] = dataset['Gender'].map({'Female':0, 'Male': 1})
<ipython-input-4-a5ff8b17c4c4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Geography'] = dataset['Geography'].map({'France':0, 'Spain': 1, 'Germany': 2})


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_train

array([[ 0.35649971, -0.90598864,  0.91324755, ...,  0.80843615,
         0.64920267,  0.97481699],
       [-0.20389777,  1.50315516,  0.91324755, ...,  0.80843615,
         0.64920267,  0.97481699],
       [-0.96147213,  0.29858326,  0.91324755, ..., -0.91668767,
         0.64920267, -1.02583358],
       ...,
       [ 0.86500853, -0.90598864, -1.09499335, ...,  2.53355998,
        -1.54035103, -1.02583358],
       [ 0.15932282, -0.90598864,  0.91324755, ..., -0.91668767,
         0.64920267, -1.02583358],
       [ 0.47065475,  1.50315516,  0.91324755, ..., -0.91668767,
         0.64920267,  0.97481699]])

## Building the Neural Network

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(6, activation='relu'),    
    tf.keras.layers.Dense(6, activation='relu'),    
    tf.keras.layers.Dense(1, activation='sigmoid') 
])

In [9]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [10]:
model.fit(x_train, y_train, batch_size = 32, epochs = 80)

Epoch 1/80
250/250 [==============================] - 0s 2ms/step - loss: 0.5082 - accuracy: 0.7884
Epoch 2/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4704 - accuracy: 0.7926
Epoch 3/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4556 - accuracy: 0.7928
Epoch 4/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4479 - accuracy: 0.7945
Epoch 5/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4425 - accuracy: 0.7969
Epoch 6/80
250/250 [==============================] - 0s 1ms/step - loss: 0.4392 - accuracy: 0.7994
Epoch 7/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4367 - accuracy: 0.8020
Epoch 8/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4345 - accuracy: 0.8055
Epoch 9/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4325 - accuracy: 0.8061
Epoch 10/80
250/250 [==============================] - 0s 2ms/step - loss: 0.4301 - accuracy: 0.8070

## testing

In [28]:
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=1)
print('Test accuracy:', test_acc)

63/63 [==============================] - 0s 1ms/step - loss: 0.3424 - accuracy: 0.8590
Test accuracy: 0.859000027179718


## Prediction

In [29]:
pred = model.predict(x_test)

In [40]:
predictions[10], y_test[10]

(array([ True]), 0)

### Predicting a single observation

Using the model to predict if the customer with the following informations will leave the bank:

Credit Score: 600

Geography: France

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

In [48]:
Single_Pred = model.predict(scaler.transform([[600, 0, 1, 40, 3, 60000, 2, 1, 1]]))

if Single_Pred > 0.5:
    print("Customer would leave ")
else:
     print('Customer stays')

Customer stays


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, pred)
print(cm)
accuracy_score(y_test, pred)

[[1540   67]
 [ 215  178]]


0.859